### ISSUE TITLE
Suggest using NickelDBus

### ISSUE THREAD

**Issue by shermp** [clisboa/KoboMail#1]
Hi, just saw your post over on MobileRead, looks like an interesting project!

Might I suggest investigating [NickelDBus](https://github.com/shermp/NickelDBus) for better integration with Kobo's software? Especially regarding book recanning. There would be no need for any user interaction with the "connect" dialog then.

You can even use it to display messages to the user, and a confirmation dialog is available for simple yes/no user input if desired.

Another thing you can do is listen for 'wifi connected' signals that Nickel emits, as a potential alternative to the udev rules.

API documentation for NickelDBus is [here](https://shermp.github.io/NickelDBus/ndb.html). Please excuse the Qt nature of the documentation. Substitute the Qt types for d-bus types, and you shouldn't have an issue...

One example of NickelDBus usage is in [Kobo-UNCaGED](https://github.com/shermp/Kobo-UNCaGED/blob/46c23091e7dbd486012333299659377426a8ab1c/kobo-uncaged/device/device.go#L112). NickelDBus itself also  has a fully featured (but also deprecated) Go CLI client you can use for reference as well. I keep it around for that purpose...

**Comment by clisboa** [comment]
Hi, 
Thank you for the suggestions.
I've looked into NickelDbus and ended up using the qndb tool to do the dialogs and book rescanning.
It's so much easier to just call it and don't have to click on the connect button.
I've still left the other option in case the user doesnt want to install NickelDbus.

I'll look further into integrating with Nickel signals to try and understand how exactly can I replace the udev rules.
At least I didn't found a way to simply trigger the signal "pooling", the program would need to be run at least once every boot.

Kind regards,
CL

**Comment by shermp** [comment]
Yeah, if you want to start at boot time, the udev trick is probably the way to go.

Glad you can get some use out of NickelDBus, it's why I made it after all!

**Comment by shermp** [comment]
Also, with regards to the progress bar, the next version of NickelDBus will be able to do that. Haven't quite got around to release it yet...

**Comment by clisboa** [comment]
Well, if you need a guinea pig let me know 😏

And thank you for all the work you've done 👍☺️

**Comment by shermp** [comment]
No worries.

I was thinking of adding another set of features for NDB v0.2.0, but I'm thinking I might save that for a potential v0.3.0, there has probably been enough features for v0.2.0 as it is, so hopefully the next version won't be far away.
