### ISSUE TITLE
Why GMail only?

### ISSUE THREAD

**Issue by daniele-athome** [clisboa/KoboMail#2]
You say "Only gmail atm", but the program seems to be compatible with any IMAP server. Is there any specific tecnique used in the program that makes it compatible only with GMail?

Thanks for this by the way!

**Comment by clisboa** [comment]
Hi Daniele,

That's correct, in KoboMail i use a trick to allow easier identification of the emails that are destined to be imported into the Kobo device. Gmail allows the use of +tag in the email, which means the emails sent to carlos+kobo@gmail.com are still delivered to the carlos@gmail.com account. 
With this flag we can easily filter all emails unread that have the TO field with carlos+kobo@gmail.com .
I don't know of anyother email service that allows this. If you have knowledge of other services that allow this let me know and we can try to test it.
I'm planning to add other methods, such as having [KOBO] in the subject or something like that to allow any email service that has IMAP functionalities.

Kind regards,
Carlos

**Comment by daniele-athome** [comment]
Several email services have the +tag feature, but I understand there should be a fallback method (such as the subject prefix as you said) for those who don't have that.

**Comment by clisboa** [comment]
Do you have a list of those services?
I could quickly test a few and remove that notice, while I don't add the fallback method that would allow more people to use this :)
